//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.296.
// 
#pragma warning disable 1591

namespace ForumProdApp.vcelgold {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Get_All_NodesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMessages_ByNodesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMessages_ByParamSeverityOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_UserNameOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = global::ForumProdApp.Properties.Settings.Default.ForumProdApp_vcelgold_WebService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Get_All_NodesCompletedEventHandler Get_All_NodesCompleted;
        
        /// <remarks/>
        public event GetMessages_ByNodesCompletedEventHandler GetMessages_ByNodesCompleted;
        
        /// <remarks/>
        public event GetMessages_ByParamSeverityCompletedEventHandler GetMessages_ByParamSeverityCompleted;
        
        /// <remarks/>
        public event Get_UserNameCompletedEventHandler Get_UserNameCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_All_Nodes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Get_All_Nodes() {
            object[] results = this.Invoke("Get_All_Nodes", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Get_All_NodesAsync() {
            this.Get_All_NodesAsync(null);
        }
        
        /// <remarks/>
        public void Get_All_NodesAsync(object userState) {
            if ((this.Get_All_NodesOperationCompleted == null)) {
                this.Get_All_NodesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_All_NodesOperationCompleted);
            }
            this.InvokeAsync("Get_All_Nodes", new object[0], this.Get_All_NodesOperationCompleted, userState);
        }
        
        private void OnGet_All_NodesOperationCompleted(object arg) {
            if ((this.Get_All_NodesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_All_NodesCompleted(this, new Get_All_NodesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMessages_ByNodes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMessages_ByNodes(string Selected_NodeNames, char Delimiter) {
            object[] results = this.Invoke("GetMessages_ByNodes", new object[] {
                        Selected_NodeNames,
                        Delimiter});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMessages_ByNodesAsync(string Selected_NodeNames, char Delimiter) {
            this.GetMessages_ByNodesAsync(Selected_NodeNames, Delimiter, null);
        }
        
        /// <remarks/>
        public void GetMessages_ByNodesAsync(string Selected_NodeNames, char Delimiter, object userState) {
            if ((this.GetMessages_ByNodesOperationCompleted == null)) {
                this.GetMessages_ByNodesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMessages_ByNodesOperationCompleted);
            }
            this.InvokeAsync("GetMessages_ByNodes", new object[] {
                        Selected_NodeNames,
                        Delimiter}, this.GetMessages_ByNodesOperationCompleted, userState);
        }
        
        private void OnGetMessages_ByNodesOperationCompleted(object arg) {
            if ((this.GetMessages_ByNodesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMessages_ByNodesCompleted(this, new GetMessages_ByNodesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMessages_ByParamSeverity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMessages_ByParamSeverity(string Selected_NodeNames, string msgSeverity, char Delimiter) {
            object[] results = this.Invoke("GetMessages_ByParamSeverity", new object[] {
                        Selected_NodeNames,
                        msgSeverity,
                        Delimiter});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMessages_ByParamSeverityAsync(string Selected_NodeNames, string msgSeverity, char Delimiter) {
            this.GetMessages_ByParamSeverityAsync(Selected_NodeNames, msgSeverity, Delimiter, null);
        }
        
        /// <remarks/>
        public void GetMessages_ByParamSeverityAsync(string Selected_NodeNames, string msgSeverity, char Delimiter, object userState) {
            if ((this.GetMessages_ByParamSeverityOperationCompleted == null)) {
                this.GetMessages_ByParamSeverityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMessages_ByParamSeverityOperationCompleted);
            }
            this.InvokeAsync("GetMessages_ByParamSeverity", new object[] {
                        Selected_NodeNames,
                        msgSeverity,
                        Delimiter}, this.GetMessages_ByParamSeverityOperationCompleted, userState);
        }
        
        private void OnGetMessages_ByParamSeverityOperationCompleted(object arg) {
            if ((this.GetMessages_ByParamSeverityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMessages_ByParamSeverityCompleted(this, new GetMessages_ByParamSeverityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_UserName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Get_UserName() {
            object[] results = this.Invoke("Get_UserName", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Get_UserNameAsync() {
            this.Get_UserNameAsync(null);
        }
        
        /// <remarks/>
        public void Get_UserNameAsync(object userState) {
            if ((this.Get_UserNameOperationCompleted == null)) {
                this.Get_UserNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_UserNameOperationCompleted);
            }
            this.InvokeAsync("Get_UserName", new object[0], this.Get_UserNameOperationCompleted, userState);
        }
        
        private void OnGet_UserNameOperationCompleted(object arg) {
            if ((this.Get_UserNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_UserNameCompleted(this, new Get_UserNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Get_All_NodesCompletedEventHandler(object sender, Get_All_NodesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_All_NodesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_All_NodesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetMessages_ByNodesCompletedEventHandler(object sender, GetMessages_ByNodesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMessages_ByNodesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMessages_ByNodesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetMessages_ByParamSeverityCompletedEventHandler(object sender, GetMessages_ByParamSeverityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMessages_ByParamSeverityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMessages_ByParamSeverityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Get_UserNameCompletedEventHandler(object sender, Get_UserNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_UserNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_UserNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591