//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumProdApp.vcelgold {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="vcelgold.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name Get_All_NodesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_All_Nodes", ReplyAction="*")]
        ForumProdApp.vcelgold.Get_All_NodesResponse Get_All_Nodes(ForumProdApp.vcelgold.Get_All_NodesRequest request);
        
        // CODEGEN: Generating message contract since element name Selected_NodeNames from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessages_ByNodes", ReplyAction="*")]
        ForumProdApp.vcelgold.GetMessages_ByNodesResponse GetMessages_ByNodes(ForumProdApp.vcelgold.GetMessages_ByNodesRequest request);
        
        // CODEGEN: Generating message contract since element name Selected_NodeNames from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessages_ByParamSeverity", ReplyAction="*")]
        ForumProdApp.vcelgold.GetMessages_ByParamSeverityResponse GetMessages_ByParamSeverity(ForumProdApp.vcelgold.GetMessages_ByParamSeverityRequest request);
        
        // CODEGEN: Generating message contract since element name Get_UserNameResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_UserName", ReplyAction="*")]
        ForumProdApp.vcelgold.Get_UserNameResponse Get_UserName(ForumProdApp.vcelgold.Get_UserNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_All_NodesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_All_Nodes", Namespace="http://tempuri.org/", Order=0)]
        public ForumProdApp.vcelgold.Get_All_NodesRequestBody Body;
        
        public Get_All_NodesRequest() {
        }
        
        public Get_All_NodesRequest(ForumProdApp.vcelgold.Get_All_NodesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Get_All_NodesRequestBody {
        
        public Get_All_NodesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_All_NodesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_All_NodesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ForumProdApp.vcelgold.Get_All_NodesResponseBody Body;
        
        public Get_All_NodesResponse() {
        }
        
        public Get_All_NodesResponse(ForumProdApp.vcelgold.Get_All_NodesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_All_NodesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Get_All_NodesResult;
        
        public Get_All_NodesResponseBody() {
        }
        
        public Get_All_NodesResponseBody(string Get_All_NodesResult) {
            this.Get_All_NodesResult = Get_All_NodesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessages_ByNodesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessages_ByNodes", Namespace="http://tempuri.org/", Order=0)]
        public ForumProdApp.vcelgold.GetMessages_ByNodesRequestBody Body;
        
        public GetMessages_ByNodesRequest() {
        }
        
        public GetMessages_ByNodesRequest(ForumProdApp.vcelgold.GetMessages_ByNodesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessages_ByNodesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Selected_NodeNames;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public char Delimiter;
        
        public GetMessages_ByNodesRequestBody() {
        }
        
        public GetMessages_ByNodesRequestBody(string Selected_NodeNames, char Delimiter) {
            this.Selected_NodeNames = Selected_NodeNames;
            this.Delimiter = Delimiter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessages_ByNodesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessages_ByNodesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ForumProdApp.vcelgold.GetMessages_ByNodesResponseBody Body;
        
        public GetMessages_ByNodesResponse() {
        }
        
        public GetMessages_ByNodesResponse(ForumProdApp.vcelgold.GetMessages_ByNodesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessages_ByNodesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMessages_ByNodesResult;
        
        public GetMessages_ByNodesResponseBody() {
        }
        
        public GetMessages_ByNodesResponseBody(string GetMessages_ByNodesResult) {
            this.GetMessages_ByNodesResult = GetMessages_ByNodesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessages_ByParamSeverityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessages_ByParamSeverity", Namespace="http://tempuri.org/", Order=0)]
        public ForumProdApp.vcelgold.GetMessages_ByParamSeverityRequestBody Body;
        
        public GetMessages_ByParamSeverityRequest() {
        }
        
        public GetMessages_ByParamSeverityRequest(ForumProdApp.vcelgold.GetMessages_ByParamSeverityRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessages_ByParamSeverityRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Selected_NodeNames;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msgSeverity;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public char Delimiter;
        
        public GetMessages_ByParamSeverityRequestBody() {
        }
        
        public GetMessages_ByParamSeverityRequestBody(string Selected_NodeNames, string msgSeverity, char Delimiter) {
            this.Selected_NodeNames = Selected_NodeNames;
            this.msgSeverity = msgSeverity;
            this.Delimiter = Delimiter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessages_ByParamSeverityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessages_ByParamSeverityResponse", Namespace="http://tempuri.org/", Order=0)]
        public ForumProdApp.vcelgold.GetMessages_ByParamSeverityResponseBody Body;
        
        public GetMessages_ByParamSeverityResponse() {
        }
        
        public GetMessages_ByParamSeverityResponse(ForumProdApp.vcelgold.GetMessages_ByParamSeverityResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessages_ByParamSeverityResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMessages_ByParamSeverityResult;
        
        public GetMessages_ByParamSeverityResponseBody() {
        }
        
        public GetMessages_ByParamSeverityResponseBody(string GetMessages_ByParamSeverityResult) {
            this.GetMessages_ByParamSeverityResult = GetMessages_ByParamSeverityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_UserNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_UserName", Namespace="http://tempuri.org/", Order=0)]
        public ForumProdApp.vcelgold.Get_UserNameRequestBody Body;
        
        public Get_UserNameRequest() {
        }
        
        public Get_UserNameRequest(ForumProdApp.vcelgold.Get_UserNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Get_UserNameRequestBody {
        
        public Get_UserNameRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_UserNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_UserNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public ForumProdApp.vcelgold.Get_UserNameResponseBody Body;
        
        public Get_UserNameResponse() {
        }
        
        public Get_UserNameResponse(ForumProdApp.vcelgold.Get_UserNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_UserNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Get_UserNameResult;
        
        public Get_UserNameResponseBody() {
        }
        
        public Get_UserNameResponseBody(string Get_UserNameResult) {
            this.Get_UserNameResult = Get_UserNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ForumProdApp.vcelgold.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ForumProdApp.vcelgold.WebService1Soap>, ForumProdApp.vcelgold.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ForumProdApp.vcelgold.Get_All_NodesResponse ForumProdApp.vcelgold.WebService1Soap.Get_All_Nodes(ForumProdApp.vcelgold.Get_All_NodesRequest request) {
            return base.Channel.Get_All_Nodes(request);
        }
        
        public string Get_All_Nodes() {
            ForumProdApp.vcelgold.Get_All_NodesRequest inValue = new ForumProdApp.vcelgold.Get_All_NodesRequest();
            inValue.Body = new ForumProdApp.vcelgold.Get_All_NodesRequestBody();
            ForumProdApp.vcelgold.Get_All_NodesResponse retVal = ((ForumProdApp.vcelgold.WebService1Soap)(this)).Get_All_Nodes(inValue);
            return retVal.Body.Get_All_NodesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ForumProdApp.vcelgold.GetMessages_ByNodesResponse ForumProdApp.vcelgold.WebService1Soap.GetMessages_ByNodes(ForumProdApp.vcelgold.GetMessages_ByNodesRequest request) {
            return base.Channel.GetMessages_ByNodes(request);
        }
        
        public string GetMessages_ByNodes(string Selected_NodeNames, char Delimiter) {
            ForumProdApp.vcelgold.GetMessages_ByNodesRequest inValue = new ForumProdApp.vcelgold.GetMessages_ByNodesRequest();
            inValue.Body = new ForumProdApp.vcelgold.GetMessages_ByNodesRequestBody();
            inValue.Body.Selected_NodeNames = Selected_NodeNames;
            inValue.Body.Delimiter = Delimiter;
            ForumProdApp.vcelgold.GetMessages_ByNodesResponse retVal = ((ForumProdApp.vcelgold.WebService1Soap)(this)).GetMessages_ByNodes(inValue);
            return retVal.Body.GetMessages_ByNodesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ForumProdApp.vcelgold.GetMessages_ByParamSeverityResponse ForumProdApp.vcelgold.WebService1Soap.GetMessages_ByParamSeverity(ForumProdApp.vcelgold.GetMessages_ByParamSeverityRequest request) {
            return base.Channel.GetMessages_ByParamSeverity(request);
        }
        
        public string GetMessages_ByParamSeverity(string Selected_NodeNames, string msgSeverity, char Delimiter) {
            ForumProdApp.vcelgold.GetMessages_ByParamSeverityRequest inValue = new ForumProdApp.vcelgold.GetMessages_ByParamSeverityRequest();
            inValue.Body = new ForumProdApp.vcelgold.GetMessages_ByParamSeverityRequestBody();
            inValue.Body.Selected_NodeNames = Selected_NodeNames;
            inValue.Body.msgSeverity = msgSeverity;
            inValue.Body.Delimiter = Delimiter;
            ForumProdApp.vcelgold.GetMessages_ByParamSeverityResponse retVal = ((ForumProdApp.vcelgold.WebService1Soap)(this)).GetMessages_ByParamSeverity(inValue);
            return retVal.Body.GetMessages_ByParamSeverityResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ForumProdApp.vcelgold.Get_UserNameResponse ForumProdApp.vcelgold.WebService1Soap.Get_UserName(ForumProdApp.vcelgold.Get_UserNameRequest request) {
            return base.Channel.Get_UserName(request);
        }
        
        public string Get_UserName() {
            ForumProdApp.vcelgold.Get_UserNameRequest inValue = new ForumProdApp.vcelgold.Get_UserNameRequest();
            inValue.Body = new ForumProdApp.vcelgold.Get_UserNameRequestBody();
            ForumProdApp.vcelgold.Get_UserNameResponse retVal = ((ForumProdApp.vcelgold.WebService1Soap)(this)).Get_UserName(inValue);
            return retVal.Body.Get_UserNameResult;
        }
    }
}
